#!/usr/bin/env bash
#set -x

DIR=$(dirname $0)
cd "$DIR" || exit 1

. ./.venv/bin/activate

export PYTHONPATH="$PWD/active_collab_app$PWD/active_collab_api:$PYTHONPATH"
exec python3 active_collab_app/main.py "$@"
