---
# run "docker compose up -d"

volumes:
  mariadb_vol:
  mariadb_backup:
  active_collab_upload:
  active_collab_thumbnails:

services:

  db:
    image: mariadb
    env_file:
      - env
    volumes:
      - mariadb_vol:/var/lib/mysql
      - mariadb_backup:/backup-volume

  # the original adminer is not maintained anymore
  # new: https://hub.docker.com/r/shyim/adminerevo
  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  active-collab-server:
    build:
      context: .
    image: active-collab-server
    restart: always
    ports:
      - "8008:8008"  # internal and external port must be same otherwise the check "URL rewriting" fails!
    env_file:
      - env
    volumes:
      - active_collab_upload:/var/www/html/upload
      - active_collab_thumbnails:/var/www/html/thumbnails
    depends_on:
      - db



